# Generated by Django 6.0 on 2026-01-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_alter_producto_options_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_producto_por_categoria'),
        ),
    ]
